version: 2

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: submodules
          command: git submodule init && git submodule update
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            export PIPENV_VENV_IN_PROJECT=~/code
            pipenv install
      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: Generate Corresponding Proto classes
          command: |
            mkdir -p covidsafe/services
            pipenv run python -m grpc_tools.protoc -I covidsafe/proto --python_out=covidsafe/services --grpc_python_out=covidsafe/services covidsafe/proto/covidsafe.proto
      - run:
          name: Check Linting
          command: pipenv run pylint covidsafe --ignore=services
